"""empty message

Revision ID: 46b6a9d5854c
Revises: a85959ee18a
Create Date: 2014-08-25 01:23:23.767000

"""

# revision identifiers, used by Alembic.
revision = '46b6a9d5854c'
down_revision = 'a85959ee18a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
