"""empty message

Revision ID: 1a0954d42e80
Revises: 46b6a9d5854c
Create Date: 2014-08-25 15:05:37.303000

"""

# revision identifiers, used by Alembic.
revision = '1a0954d42e80'
down_revision = '46b6a9d5854c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
