"""empty message

Revision ID: 31c7c69cdd60
Revises: 1a0954d42e80
Create Date: 2014-08-25 15:41:23.173000

"""

# revision identifiers, used by Alembic.
revision = '31c7c69cdd60'
down_revision = '1a0954d42e80'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
