"""empty message

Revision ID: a85959ee18a
Revises: None
Create Date: 2014-08-24 20:54:09.245000

"""

# revision identifiers, used by Alembic.
revision = 'a85959ee18a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
